<Project>

  <PropertyGroup>
    <Authors>wherewhere</Authors>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Copyright>Copyright © 2017 - 2026 wherewhere. All Rights Reserved.</Copyright>
    <Deterministic>true</Deterministic>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <LangVersion>latest</LangVersion>
    <PackageIconUrl>https://raw.githubusercontent.com/wherewhere/Indexerable/main/logo.png</PackageIconUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/wherewhere/Indexerable</PackageProjectUrl>
    <PackageReleaseNotes>https://github.com/wherewhere/Indexerable/releases</PackageReleaseNotes>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageTags>LINQ;IReadOnlyList;Sequences;Lazy;Indexer</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/wherewhere/Indexerable</RepositoryUrl>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Title>Indexerable - LINQ for IReadOnlyList</Title>
    <VersionPrefix>0.0.1</VersionPrefix>
    <Description>LINQ-style operators for IReadOnlyList collections, with lazy evaluation and indexed access.</Description>
  </PropertyGroup>

  <PropertyGroup>
    <FullTargets Condition="'$(FullTargets)' == ''">false</FullTargets>
    <IsWindows Condition="'$(IsWindows)' == ''">false</IsWindows>
    <IsWindows Condition="$([MSBuild]::IsOSPlatform('Windows')) == 'true' OR '$(Platform)' == 'Windows NT'">true</IsWindows>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'native'">
    <DebugType>Full</DebugType>
    <DefineConstants>$(DefineConstants);WINDOWS_UWP;WINRT</DefineConstants>
    <NuGetTargetMoniker Condition="'$(DesignTimeBuild)' == 'true'">native</NuGetTargetMoniker>
    <NuGetTargetMoniker Condition="'$(DesignTimeBuild)' != 'true'">UAP,Version=v10.0</NuGetTargetMoniker>
    <OutputType>winmdobj</OutputType>
    <PackageTargetFallback>uap10.0</PackageTargetFallback>
    <TargetPlatformMinVersion>10.0.10240.0</TargetPlatformMinVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'netcore5.0'">
    <NugetTargetMoniker>.NETCore,Version=v5.0</NugetTargetMoniker>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'uap10.0.15138.0'">
    <DefineConstants>$(DefineConstants);WINDOWS_UWP</DefineConstants>
    <NugetTargetMoniker>UAP,Version=v10.0</NugetTargetMoniker>
    <TargetPlatformMinVersion>10.0.15138.0</TargetPlatformMinVersion>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'uap'))">
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <DefaultLanguage>en-US</DefaultLanguage>
    <LanguageTargets>$(MSBuildExtensionsPath)\Microsoft\WindowsXaml\v$(VisualStudioVersion)\Microsoft.Windows.UI.Xaml.CSharp.targets</LanguageTargets>
    <TargetFrameworkIdentifier>.NETCore</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v5.0</TargetFrameworkVersion>
    <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
    <TargetPlatformVersion>10.0.22621.0</TargetPlatformVersion>
  </PropertyGroup>

</Project>
