<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <FullTargets>true</FullTargets>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);NU1603;NU1902;NU1903</NoWarn>
    <Nullable>enable</Nullable>
    <PackageIcon>Icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RootNamespace>Indexer</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
    <IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">true</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup>
    <CheckNotRecommendedTargetFramework>false</CheckNotRecommendedTargetFramework>
    <SuppressTfmSupportBuildWarnings>false</SuppressTfmSupportBuildWarnings>
    <TargetFrameworks>net7.0;net9.0;netcoreapp2.0;netstandard1.2;netstandard2.0</TargetFrameworks>
    <TargetFrameworks Condition="'$(IsWindows)' == 'true'">$(TargetFrameworks);net4.5;net4.7</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(FullTargets)' == 'true'">
    <NoWarn>$(NoWarn);NU1603;NU1901</NoWarn>
    <TargetFrameworks>$(TargetFrameworks);netcoreapp3.0;net6.0;netstandard1.0;netstandard2.1</TargetFrameworks>
    <TargetFrameworks Condition="'$(IsWindows)' == 'true' and '$(GITHUB_ACTIONS)' != 'true'">$(TargetFrameworks);netcore5.0;uap10.0;wp8.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <PolySharpIncludeGeneratedTypes>
      System.Diagnostics.CodeAnalysis.DoesNotReturnAttribute
    </PolySharpIncludeGeneratedTypes>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.0'))">
    <DefineConstants>$(DefineConstants);COMP_NETSTANDARD2_0</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.1'))">
    <DefineConstants>$(DefineConstants);COMP_NETSTANDARD2_1</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net4.7'))
                         or $([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netcoreapp1.0'))
                         or (!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net1.1'))
                         and $([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.0')))">
    <DefineConstants>$(DefineConstants);HAS_VALUETUPLE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PolySharp" Version="1.16.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'wp8.0'))">
    <Reference Include="System" Pack="false" />
    <Reference Include="System.Core" Pack="false" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\logo.png" Pack="true" PackagePath="\Icon.png" />
    <None Include="..\README.md" Pack="true" PackagePath="\README.md" />
  </ItemGroup>

</Project>
